In [1]:
import numpy as np

In [2]:
ar1 = np.array([15,62,43])

In [3]:
type(ar1)

numpy.ndarray

In [4]:
ar1

array([15, 62, 43])

In [5]:
ar1 = np.array((101,"raj",25.36))

In [6]:
ar1

array(['101', 'raj', '25.36'], dtype='<U32')

In [7]:
np.array((1,2,3)) #will create one dimensional array

array([1, 2, 3])

In [8]:
np.array([(1,2,3),(4,5,6),(2,4,6)]) #will create two dimensional array

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 6]])

In [9]:
np.zeros(15) # will create 1D array of zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,4)) # will create 2D array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.zeros((3,4),dtype=int) # will create 2D array of zeros with int dtype

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
np.ones((3,4)) #will print 3x4 ones in the matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.full((3,4),(9)) #will create 3x4 array with values of 9

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [14]:
np.eye(4) #will create 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.linspace(5,25,6) #will create array of 6 values between 5 to 25

array([ 5.,  9., 13., 17., 21., 25.])

In [16]:
np.arange(10,30,3) #will create array starting from 10 to 30 with difference of 3

array([10, 13, 16, 19, 22, 25, 28])

In [17]:
np.random.rand(4,5) #will create 4x5 array with random values between 0 to 1

array([[0.63779286, 0.43779649, 0.05540278, 0.81338805, 0.66408757],
       [0.86935269, 0.00177505, 0.42796052, 0.17389976, 0.1339843 ],
       [0.94684715, 0.01752473, 0.4748147 , 0.78174504, 0.46985752],
       [0.92534655, 0.29357229, 0.54040134, 0.10623071, 0.20844517]])

In [18]:
np.random.rand(100) #will create 1D array with 100 random values between 0 to 1

array([0.22279022, 0.93445473, 0.53287934, 0.29842662, 0.92435977,
       0.67622857, 0.68393908, 0.57288071, 0.85388009, 0.65673523,
       0.3248057 , 0.45662832, 0.79176171, 0.95364126, 0.65940331,
       0.6979604 , 0.91550704, 0.06743394, 0.72418971, 0.32303893,
       0.68944223, 0.11696057, 0.57203042, 0.78657575, 0.62267279,
       0.13687138, 0.48796488, 0.7043448 , 0.65550625, 0.71618007,
       0.82997769, 0.01852086, 0.61103487, 0.13497846, 0.47606303,
       0.94356351, 0.9095923 , 0.25068935, 0.97905251, 0.65055223,
       0.55939806, 0.7653596 , 0.93590635, 0.12155845, 0.70317703,
       0.95858697, 0.85763717, 0.4312745 , 0.53785931, 0.03871798,
       0.35262369, 0.5081891 , 0.5379149 , 0.7098799 , 0.99399603,
       0.35647114, 0.68767474, 0.43069682, 0.59481466, 0.28221767,
       0.92310414, 0.30766744, 0.60911681, 0.16594747, 0.16454823,
       0.09962345, 0.9013508 , 0.81420484, 0.28568782, 0.10896367,
       0.93750117, 0.35815066, 0.58407653, 0.24100498, 0.91652

In [19]:
np.random.rand(5,5)*50 #will create 5x5 array with random values between 0 to 50

array([[ 3.12533228, 39.25571238, 37.23211414,  8.53028965,  7.06600221],
       [ 8.49042164, 47.36198022, 30.58648941, 32.66926882, 30.9964297 ],
       [46.35546809, 19.09380928, 19.82152299, 42.06789011, 18.00337242],
       [16.72476031, 46.62178293, 26.96419178, 41.22371896, 42.29443257],
       [33.82352797, 27.6217699 , 14.02550143,  6.92321113,  7.0270612 ]])

In [20]:
np.random.choice([8,2,6,1,3,7,5]) #will create single random value from the given array

np.int64(3)

In [21]:
np.random.choice([8,2,6,1,3,7,5],[3,3]) #will create 3x3 array with random values from the given array

array([[7, 8, 5],
       [8, 8, 6],
       [7, 6, 3]])

In [22]:
np.random.randint(15,size=(25)) #will create 1D array with 25 random integers between 0 to 15

array([ 9,  7,  8,  5, 12, 10,  8,  3,  0, 12, 11, 11,  7, 13,  5,  3,  0,
       12,  1,  9, 14,  5, 14,  9, 13], dtype=int32)

In [23]:
np.random.randint(10,size=(5,3)) #will create 5x3 array with random integers between 0 to 10

array([[4, 4, 1],
       [0, 8, 9],
       [1, 2, 1],
       [4, 1, 0],
       [9, 9, 3]], dtype=int32)

In [24]:
np.random.randint(15,25,size=(4,3)) #will create 4x3 array with random integers between 15 to 25

array([[16, 16, 23],
       [24, 16, 17],
       [17, 19, 21],
       [19, 18, 20]], dtype=int32)