In [1]:
import numpy as np

In [2]:
ar1 = np.array([15,62,43])

In [3]:
type(ar1)

numpy.ndarray

In [4]:
ar1

array([15, 62, 43])

In [5]:
ar1 = np.array((101,"raj",25.36))

In [6]:
ar1

array(['101', 'raj', '25.36'], dtype='<U32')

In [7]:
np.array((1,2,3)) #will create one dimensional array

array([1, 2, 3])

In [8]:
np.array([(1,2,3),(4,5,6),(2,4,6)]) #will create two dimensional array

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 6]])

In [9]:
np.zeros(15) # will create 1D array of zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,4)) # will create 2D array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.zeros((3,4),dtype=int) # will create 2D array of zeros with int dtype

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [12]:
np.ones((3,4)) #will print 3x4 ones in the matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.full((3,4),(9)) #will create 3x4 array with values of 9

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [14]:
np.eye(4) #will create 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.linspace(5,25,6) #will create array of 6 values between 5 to 25

array([ 5.,  9., 13., 17., 21., 25.])

In [16]:
np.arange(10,30,3) #will create array starting from 10 to 30 with difference of 3

array([10, 13, 16, 19, 22, 25, 28])

In [17]:
np.random.rand(4,5) #will create 4x5 array with random values between 0 to 1

array([[0.85604088, 0.0082815 , 0.5290297 , 0.53156449, 0.00223334],
       [0.50923153, 0.00266558, 0.27481855, 0.07184233, 0.88714738],
       [0.86847827, 0.19183956, 0.81699482, 0.56621251, 0.75660066],
       [0.33021205, 0.96566285, 0.78410905, 0.80834978, 0.11697076]])

In [18]:
np.random.rand(100) #will create 1D array with 100 random values between 0 to 1

array([0.04756685, 0.85488326, 0.93401706, 0.7846953 , 0.72502628,
       0.58384765, 0.81251453, 0.42539559, 0.45735058, 0.04549817,
       0.51357557, 0.00926525, 0.10191319, 0.03928008, 0.39282201,
       0.99110503, 0.45897768, 0.99975899, 0.61557184, 0.91677531,
       0.48172128, 0.42995109, 0.1454323 , 0.71352452, 0.68486266,
       0.19340375, 0.08685584, 0.09162232, 0.58767744, 0.72594386,
       0.07169338, 0.33890307, 0.79525616, 0.03869756, 0.11682231,
       0.22046934, 0.18772617, 0.93127958, 0.56902182, 0.37977682,
       0.26247158, 0.5278904 , 0.52172429, 0.79957402, 0.76740158,
       0.47029664, 0.56329891, 0.63840641, 0.82702614, 0.41922508,
       0.93857705, 0.76043941, 0.34268667, 0.32331717, 0.6463238 ,
       0.76461841, 0.14579887, 0.16510224, 0.03258856, 0.12121446,
       0.57942262, 0.18653495, 0.99271086, 0.66966178, 0.07481955,
       0.92926716, 0.23912676, 0.84568949, 0.1467589 , 0.76981782,
       0.43777211, 0.72771214, 0.79117038, 0.22233873, 0.81936

In [19]:
np.random.rand(5,5)*50 #will create 5x5 array with random values between 0 to 50

array([[43.56419564, 27.01751801,  3.952562  , 43.96913991, 11.46028789],
       [31.60619266, 30.9769505 , 23.81649116,  3.23089927, 39.67315713],
       [21.77333241, 34.52490511, 46.36869514, 11.55149689, 45.22316474],
       [27.27789979, 30.05128134,  6.79480146, 20.49715222, 32.94560384],
       [42.8893227 , 47.69162209, 16.25706725, 15.53864408, 28.6925842 ]])

In [20]:
np.random.choice([8,2,6,1,3,7,5]) #will create single random value from the given array

np.int64(7)

In [21]:
np.random.choice([8,2,6,1,3,7,5],[3,3]) #will create 3x3 array with random values from the given array

array([[8, 7, 2],
       [7, 3, 3],
       [5, 8, 8]])

In [22]:
np.random.randint(15,size=(25)) #will create 1D array with 25 random integers between 0 to 15

array([12,  7,  5,  4, 14, 12,  5,  4,  5,  6,  6, 13, 11, 12, 12, 10, 12,
        9,  0,  7, 12, 10,  4,  3,  6], dtype=int32)

In [23]:
np.random.randint(10,size=(5,3)) #will create 5x3 array with random integers between 0 to 10

array([[6, 5, 7],
       [3, 3, 2],
       [3, 2, 5],
       [0, 5, 0],
       [9, 6, 6]], dtype=int32)

In [24]:
np.random.randint(15,25,size=(4,3)) #will create 4x3 array with random integers between 15 to 25

array([[23, 18, 15],
       [22, 18, 21],
       [20, 16, 16],
       [18, 17, 16]], dtype=int32)